### ISSUE TITLE
Problems on Redmi 8 after installing a privileged app

### ISSUE THREAD

**Issue by Triplexit** [msimonides/homerplayer2#1]
After factory reset on Redmi 8 and installing the app via QR code, the app can't find the book folder.  Homer 1 asks to install file manager app (despite having 2 different file managers installed), Homer 2 just crashes after pressing “add folder” button.  

It seems that installing via QR code does not allow Redmi to complete the initial setup. Many default apps that appear after normal installation are missing if you install Homer Kiosk Setup first.  

I backed up all default apps before resetting the phone, installed Homer Kiosk Setup, and then restored the backed up apps, but it didn't help.

**Comment by msimonides** [comment]
Thank you for a detailed report. Could you install Homer Kiosk Setup with the following QR code? I have updated the provisioning step to keep system apps enabled. I expect all the apps to now be there but I have no Xiaomi devices to test with.

> Homer 1 asks to install file manager app (despite having 2 different file managers installed), Homer 2 just crashes after pressing “add folder” button.

The error the message about file managers is a bit misleading (part of why I let Homer 2 crash until now). The issue is that Homer Player needs permission to access the audiobooks folder and this is granted by a system app.

![kiosk-setup-1 0 4](https://github.com/msimonides/homerplayer2/assets/6563974/530c1021-2355-4648-aca3-6e6298590e2c)

**Comment by Triplexit** [comment]
Unfortunately, Redmi 8 does not read this QR code. I see it on the screen, trying to move closer, further, but all to no avail (Samsung reads it without a problem). I scanned with Redmi the QR code at https://msimonides.github.io/homerplayer2/ and it was caught instantly. Now when trying to add a book folder I see the following. 
![Screenshot_2024-05-23-13-50-32-682_com studio4plus homerplayer2](https://github.com/msimonides/homerplayer2/assets/170247842/f4bdc569-c16c-4c69-b85b-f1413a7a14d2)

**Comment by msimonides** [comment]
>Unfortunately, Redmi 8 does not read this QR code. I see it on the screen, trying to move closer, further, but all to no avail (Samsung reads it without a problem).

It could be because there's not enough white space around it in the comments here? I'll put the QR code for the new version on the website https://msimonides.github.io/homerplayer2/ today (1-2hr).

**Comment by Triplexit** [comment]
You are right, the scanning problem was due to the lack of white margins. I reinstalled the program with the new QR, but still got the message "Unable to open file chooser". It should be noted that with a regular installation there's no browsing problems in Homer 2.
________________________________

**Comment by msimonides** [comment]
Please try again with the QR code on the website https://msimonides.github.io/homerplayer2/, I have updated it. The QR code setup should now retain all the apps including the file chooser (I have tested this with a Samsung phone, I hope it works the same with Xiaomi).

**Comment by Triplexit** [comment]
You did it: the problem is solved! Everything works fine, thank you so much!
